/**
 * mcp.test — the MCP scope vocabulary (S249).
 *
 * These restate the wire values independently of `src/mcp.ts` rather than
 * reading them back off it, so an accidental edit to a literal is a RED here
 * and not a silently agreed-upon change. The expected values are transcribed
 * from `phlix-hub/src/Mcp/McpScopes.php` and `McpTokenService.php`.
 *
 * @copyright 2026 Joe Huss <detain@interserver.net>
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { MCP_SCOPE, MCP_SCOPES, MCP_TOKEN_PREFIX } from '../src/mcp';

describe('mcp scope vocabulary', () => {
  it('matches the hub McpScopes constants', () => {
    expect(MCP_SCOPE.SERVERS_READ).toBe('mcp:servers:read');
    expect(MCP_SCOPE.LIBRARY_READ).toBe('mcp:library:read');
    expect(MCP_SCOPE.PLAYBACK_READ).toBe('mcp:playback:read');
    expect(MCP_SCOPE.PLAYBACK_CONTROL).toBe('mcp:playback:control');
  });

  it('enumerates every scope in McpScopes::all() order', () => {
    // Order is part of the stored representation (`McpScopes::parse()` emits in
    // this order into `mcp_tokens.scopes`), so this is an ORDERED comparison of
    // the whole list, never a membership check.
    expect([...MCP_SCOPES]).toEqual([
      'mcp:servers:read',
      'mcp:library:read',
      'mcp:playback:read',
      'mcp:playback:control',
    ]);
  });

  it('exposes every MCP_SCOPE member in MCP_SCOPES, and nothing else', () => {
    // Guards the two halves drifting apart: a constant added to MCP_SCOPE but
    // forgotten in the list would be invisible to the ordered check above only
    // if that check were also updated, so compare the sets directly.
    expect([...MCP_SCOPES].slice().sort()).toEqual(Object.values(MCP_SCOPE).slice().sort());
  });

  it('is non-vacuous: at least 4 scopes, each a non-empty mcp: string', () => {
    // Anti-vacuity floor. A consumer asserting equality against this list must
    // be able to trust that an empty or undefined export cannot pass as "equal".
    expect(MCP_SCOPES.length).toBeGreaterThanOrEqual(4);
    for (const scope of MCP_SCOPES) {
      expect(typeof scope).toBe('string');
      expect(scope.startsWith('mcp:')).toBe(true);
      expect(scope.length).toBeGreaterThan('mcp:'.length);
    }
  });

  it('has no duplicate members', () => {
    expect(new Set(MCP_SCOPES).size).toBe(MCP_SCOPES.length);
  });

  it('matches McpTokenService::TOKEN_PREFIX', () => {
    expect(MCP_TOKEN_PREFIX).toBe('phlix-mcp-');
  });
});

describe('the committed dist/mcp-scopes.json artifact', () => {
  // phlix-hub is PHP with no Node in CI, so it pins against this JSON rather
  // than importing the package. The artifact is COMMITTED, which means it can
  // go stale: someone edits src/mcp.ts, skips `npm run build`, and the hub then
  // gates against a vocabulary this package no longer declares. This is the
  // detector for that. In CI `npm run build` runs before `npm run test:run`, so
  // a stale committed file is caught even if it was regenerated by that build.
  const artifact = JSON.parse(
    readFileSync(resolve(__dirname, '..', 'dist', 'mcp-scopes.json'), 'utf8'),
  ) as { scopes: string[]; tokenPrefix: string };

  it('is non-vacuous', () => {
    expect(Array.isArray(artifact.scopes)).toBe(true);
    expect(artifact.scopes.length).toBeGreaterThanOrEqual(4);
    expect(typeof artifact.tokenPrefix).toBe('string');
    expect(artifact.tokenPrefix.length).toBeGreaterThan(0);
  });

  it('matches MCP_SCOPES exactly, in order', () => {
    expect(artifact.scopes).toEqual([...MCP_SCOPES]);
  });

  it('matches MCP_TOKEN_PREFIX', () => {
    expect(artifact.tokenPrefix).toBe(MCP_TOKEN_PREFIX);
  });
});
